[package]
name = "raspberry-pi-ir-hat-network-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
log = "0.4.22"
log4rs = "1.3.0"
tokio = { version = "1.40.0", features = ["full"] }
