#ifndef _config_generated_h_
#define _config_generated_h_
#define GIT_COMMIT "b78dab545b56621f16a87002227c959df9aa0747"
#define CURREF_PORT GPIOA
#define CURREF_PIN LL_GPIO_PIN_0
#define ADC1_IN0_PORT GPIOA
#define ADC1_IN0_PIN LL_GPIO_PIN_0
#define SYS_SWDIO_PORT GPIOA
#define SYS_SWDIO_PIN LL_GPIO_PIN_13
#define SYS_SWCLK_PORT GPIOA
#define SYS_SWCLK_PIN LL_GPIO_PIN_14
#define USART2_TX_PORT GPIOA
#define USART2_TX_PIN LL_GPIO_PIN_2
#define USART2_RX_PORT GPIOA
#define USART2_RX_PIN LL_GPIO_PIN_3
#define CUR1_PORT GPIOA
#define CUR1_PIN LL_GPIO_PIN_4
#define ADC1_IN4_PORT GPIOA
#define ADC1_IN4_PIN LL_GPIO_PIN_4
#define CUR2_PORT GPIOA
#define CUR2_PIN LL_GPIO_PIN_5
#define ADC1_IN5_PORT GPIOA
#define ADC1_IN5_PIN LL_GPIO_PIN_5
#define S_TIM3_CH1_PORT GPIOA
#define S_TIM3_CH1_PIN LL_GPIO_PIN_6
#define IR_IN_LED_PORT GPIOA
#define IR_IN_LED_PIN LL_GPIO_PIN_7
#define GPIO_Output_PORT GPIOA
#define GPIO_Output_PIN LL_GPIO_PIN_7
#define USART1_TX_PORT GPIOB
#define USART1_TX_PIN LL_GPIO_PIN_6
#define USART1_RX_PORT GPIOB
#define USART1_RX_PIN LL_GPIO_PIN_7
#define IR_OUT_PORT GPIOB
#define IR_OUT_PIN LL_GPIO_PIN_9
#endif
