remotes:
  pioneer:
    interval: 25
    repeat: 2
    buttons:
      power:
        single_shot: true
        debounce: 1000
        ir_signals:
          - protocol: NEC
            address: 170
            command: 28
  denon:
    interval: 25
    repeat: 2
    buttons:
      power:
        single_shot: true 
        debounce: 1000
        ir_signals:
          - protocol: Denon
            address: 8
            command: 135
      volume_up:
        debounce: 250
        ir_signals:
          - protocol: Denon
            address: 8
            command: 79
      volume_down:
        debounce: 250
        ir_signals:
          - protocol: Denon
            address: 8
            command: 143
